spring:
  application.name: test-ci
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: 
    password: 
    driverClassName: org.h2.Driver
    
security:
  basic.enabled: false
  user.password: unused 